@startuml
title Activity Diagram (Запрос на набор)
|Пользователь|
start
:Запрос доступа к набору;

|Владелец набора|
:Получить уведомление;
if (Разрешить доступ?) then (Да)
  :Открыть доступ;
else (Нет)
  :Отклонить запрос;
endif

|Система|
:Синхронизировать изменения;
stop
@enduml