@startuml
title Activity Diagram (Создание набора карточек)

start
:Пользователь выбирает "Новый набор";
:Ввести название и описание;

partition "Настройки доступа" {
    if (Тип набора?) then (Приватный)
        :Только для владельца;
    else (Публичный)
        :Разрешить запросы доступа;
    endif
}

if (Отредактировать набор?) then (да)
    
else (нет)
    stop
endif
repeat
    :Добавить карточку:
    :Ввести вопрос ответ;
    :Добавить теги;
repeat while (Еще карточки?) is (да) not (нет)

stop
@enduml