@startuml
title Activity Diagram (Прохождение теста)

start
:Пользователь запускает тест;
if (Набор карточек пуст?) then (Да)
  :Показать сообщение "Нет карточек";
  stop
else (Нет)
  repeat
    :Показать карточку;
    :Пользователь отвечает;
    if (Ответ верный?) then (Да)
      :Добавить балл;
    else (Нет)
      :Пропустить;
    endif
  repeat while (Есть еще карточки?) is (Да)
  ->Нет;
  :Показать результаты;
stop
@enduml