@startuml

title Sequence Diagram (Вход в систему)

actor Гость
participant "Система аутентификации" as Auth
participant "База данных" as DB

Гость -> Auth : Запрос на вход (логин, пароль)
Auth -> DB : Проверить логин и пароль
DB -> Auth : Ответ (успешно/неуспешно)
alt Если данные верные
    Auth -> Гость : Генерация токена (JWT)
    Auth -> Гость : Ответ (токен)
else Если данные неверные
    Auth -> Гость : Ошибка: Неверный логин или пароль
end
@enduml
