@startuml
title Sequence Diagram (Одобрение заявки на набор карточек)
actor Пользователь
actor Владелец_набора
participant "Система доступа к наборам" as AccessSystem
participant "База данных" as DB

' Пользователь отправляет запрос
Пользователь -> AccessSystem : Запросить доступ к публичному набору
AccessSystem -> DB : Сохранить запрос в базе данных
AccessSystem -> Владелец_набора : Уведомление о запросе

' Владелец набора принимает или отклоняет запрос
Владелец_набора -> AccessSystem : Одобрить/Отклонить запрос

alt Одобрить запрос
    AccessSystem -> DB : Обновить статус запроса как "одобрен"
    AccessSystem -> Пользователь : Доступ разрешен
else Отклонить запрос
    AccessSystem -> DB : Обновить статус запроса как "отклонен"
    AccessSystem -> Пользователь : Доступ отказан
end
@enduml