@startuml

title State Diagram (Для запроса на набор карточек)

state "Запрос доступа" as Request {
  [*] --> Создан : Пользователь отправил запрос
  Создан : entry / Формирование запроса
  Создан : do / Отправить уведомление хозяину
  Создан --> Ожидание_ответа : Отправка запроса владельцу
  
  
  Ожидание_ответа --> Отклонен : Отклонен владельцем
  Отклонен : entry / Изменить статус
  Отклонен --> [*] 

  Ожидание_ответа --> Одобрен : Одобрен владельцем
  Одобрен : entry / Изменить статус
  Одобрен --> [*]
}
@enduml