@startuml

title State Diagram (Для пользователя)

state "Гость" as Guest {
  [*] --> Ожидание_входа
  Ожидание_входа : Может зарегистрироваться или войти
  Ожидание_входа : entry / Показывать экран входа
}

state "Пользователь" as User {
  [*] --> Главная_страница
  Главная_страница : Может управлять наборами, проходить тесты, делать запросы
  Главная_страница : entry / Загрузить данные пользователя
  Главная_страница : do / Ожидание действий пользователя
  Главная_страница : exit / Очистка временных данных
  Главная_страница --> Выход : Выход из системы
  Выход : entry / Завершение сессии
  Выход --> Guest
}

Guest --> User : Вход в систему
User --> Guest : Выход из системы
Выход  --> [*]
@enduml