@startuml

title State Diagram (Для набора карточек)

state "Набор карточек" as Deck {
  [*] --> Создан
  Создан : Можно открыть
  Создан : entry / Создание нового набора
  Создан : do / Ввести название
  Создан : do / Выбрать тип (публичный/приватный)
  Создан : exit / Сохранение изменений
  Создан --> Открыт 
  Создан --> Удален 
  Открыт : do / Показать карточки
  Открыт --> Открыт_Сторонним_пользователем : Открыт сторонним пользователем

  Открыт_Сторонним_пользователем : Открыт сторонним пользователем
  Открыт_Сторонним_пользователем : entry / Показанные карточки
  Открыт_Сторонним_пользователем : do / Учится по карточкам
  Открыт_Сторонним_пользователем : do / Проходить тесты
  Открыт_Сторонним_пользователем : exit / Закрыт

  Открыт --> Открыт_Владельцем : Открыт владельцем
  Открыт_Владельцем : entry / Показанные карточки
  Открыт_Владельцем : do / Учится по карточкам
  Открыт_Владельцем : do / Проходить тесты
  Открыт_Владельцем : do / Редактировать карточки
  Открыт_Владельцем : do / Редактировать набор
  Открыт_Владельцем : exit / Закрыт
  Удален --> [*]
}


@enduml